### ISSUE TITLE
Not able to deploy lab successfully

### ISSUE THREAD

**Issue by APersondek** [pluralsight/PS-AutoLab-Env#205] opened 2019-11-26 17:57 UTC
Hello,

I have tried to deploy both the single server and multi role lab 3 or 4 times, and the DC spins up successfully without issue. However, the S1, N1, and CLI1 VMs hit a non boot screen. I have attached the transcript below, please let me know what I can do to resolve or further assist to resolve this issue?

Thanks,

Al 

![S1](https://user-images.githubusercontent.com/58229244/69658748-a2438f80-1031-11ea-8740-65121456fa88.PNG)
![CLI1](https://user-images.githubusercontent.com/58229244/69658749-a2438f80-1031-11ea-9954-eaf671a54702.PNG)
![N1](https://user-images.githubusercontent.com/58229244/69658750-a2438f80-1031-11ea-99a2-59220546e402.PNG)

Transcript:

[PowerShell_transcript.SPO190560-L.QhMXjZuD.20191126093953.txt](https://github.com/pluralsight/PS-AutoLab-Env/files/3893307/PowerShell_transcript.SPO190560-L.QhMXjZuD.20191126093953.txt)

**Comment by jdhitsolutions** [comment] 2019-11-26 18:34
You are the second person to post the error about a missing CustomMedia.json file which I can not duplicate. And as far as I can tell that file doesn't exist nor should it be required. I'm assuming you ran Setup-Host to setup Hyper-V and the other prerequisites. What I think is happening is the VMs are getting created but not the disks.

Under C:\Autolab\MasterVirtualHardDisks do you see vhdx files? Those master disks should be used to create differencing disks under C:\Autolab\VMVirtualHardDisks You should also have ISOs under C:\Autolab\ISOs.

I pushed an update to the PowerShell gallery so make sure you are running 4.4.0. Post the output from Get-PSAutolab.

**Comment by APersondek** [comment] 2019-11-26 18:40
Jeff,

Here is what I have in MasterVirtualHard Disks and the Isos folder. I am going to run the update now and try again.

Thanks,

Al
[cid:image001.png@01D5A445.F0454D70]

[cid:image002.png@01D5A445.F0454D70]

**Comment by jdhitsolutions** [comment] 2019-11-26 18:57
The screen shots didn't post.

**Comment by APersondek** [comment] 2019-11-26 19:04
![ISOs](https://user-images.githubusercontent.com/58229244/69664112-8e515b00-103c-11ea-9ba2-e08dbb28a248.PNG)
![HDDs](https://user-images.githubusercontent.com/58229244/69664113-8e515b00-103c-11ea-961a-c1519237eb94.PNG)

**Comment by APersondek** [comment] 2019-11-26 19:06
Jeff,
Yes, I am running 4.4.0 as well

**Comment by APersondek** [comment] 2019-11-26 19:25
Jeff,

Here is the latest transcript. DC1, and S1 are up, however both CLI1 and N1 failed to boot. Please let me know if I can assist you further in troubleshooting this issue.
[PowerShell_transcript.SPO190560-L.cV+TaRBT.20191126105542.txt](https://github.com/pluralsight/PS-AutoLab-Env/files/3893683/PowerShell_transcript.SPO190560-L.cV%2BTaRBT.20191126105542.txt)

Thanks,
Al

**Comment by jdhitsolutions** [comment] 2019-11-26 20:06
The master disks are created, which is good. After you run the setup, you should see differencing disks under C:\Autolab\VMVirtualHardDisks for each VM. I suspect one or more isn't getting created. Run Get-PSAutolabsetting and post the results. The other thing that comes to mind is that you don't have enough disk space.  I may have to do some in-depth debugging of the lability module to see where this is getting called. But this is a short holiday week; I can't make any promises on a timeframe. 

You might wipe the lab and see if you can set up anything like SingleServer or Windows10 configurations without error.

**Comment by APersondek** [comment] 2019-11-26 20:20
Jeff,

Thank you, I understand the timing of the short holiday week. I am using a 500 GB nvme SSD with 295 GB of free space. here is the Get-PSAutolabsetting without the lab running:

PS C:\Autolab\Configurations\MultiRole> get-PSAutolabsetting                                                            

PSVersion     : 5.1.18362.145
PSEdition     : Desktop
OS            : Microsoft Windows 10 Pro
IsElevated    : True
HyperV        : 10.0.18362.1
PSAutolab     : 4.4.0
Lability      : 0.18.0
Pester        : 4.9.0
MemoryGB      : 16
PctFreeMemory : 63.01
PS C:\Autolab\Configurations\MultiRole>  

and here it is with the lab running:
PS C:\Autolab\Configurations\MultiRole> get-PSAutolabsetting                                                            

PSVersion     : 5.1.18362.145
PSEdition     : Desktop
OS            : Microsoft Windows 10 Pro
IsElevated    : True
HyperV        : 10.0.18362.1
PSAutolab     : 4.4.0
Lability      : 0.18.0
Pester        : 4.9.0
MemoryGB      : 16
PctFreeMemory : 17.49

Yes, I am trying to make this work with 16 GB of memory, but that does not seem to be the issue.

here is the screen shot of C:\Autolab\VMVirtualHardDisks for each VM:
![VM-Disks](https://user-images.githubusercontent.com/58229244/69669648-1f2d3400-1047-11ea-8539-c97e9b2b3178.PNG)

**Comment by jdhitsolutions** [comment] 2019-11-26 20:51
You have plenty of resources. I'm running the same version of Windows and everything and don't have this issue. When you get a chance, try the Windows10 configuration. It creates a different VM so you should be able to run the config side by side. Then we'll know if the problem is limited to the Multirole configuration.  You might also wipe the lab and try the PowerShellLab to see if that works.

**Comment by APersondek** [comment] 2019-11-26 20:56
Jeff,

I wiped the lab and tried to setup the windows 10 vm without success.
![win10ENT](https://user-images.githubusercontent.com/58229244/69672077-37ec1880-104c-11ea-92eb-b855e28d918b.PNG)

**Comment by jdhitsolutions** [comment] 2019-11-26 21:17
Darn. I'll have to dig deeper to figure out why your computer won't create the proper disk image.

**Comment by APersondek** [comment] 2019-11-26 21:22
Jeff,
Thank you, please let me know if you need anything else from me to help troubleshoot /correct this issue.
Al

**Comment by APersondek** [comment] 2019-11-27 16:08
Jeff,
I know you are on a short schedule this week, but first thing this morning I deleted the the master VHDX files, so the script would attempt to recreate them, and now I am getting the following error, and the script does not finish running at all.

![setup-error](https://user-images.githubusercontent.com/58229244/69739769-20b13780-10ed-11ea-8de6-44044c12624b.PNG)

**Comment by jdhitsolutions** [comment] 2019-11-27 16:39
Uggh. I tried something similar by renaming one of the master vhdx files and setup ran fine, re-creating the master vhdx file. Something in the Lability module is out of whack. Someone else reported that semaphore timeout error. They ended up re-installing Windows.  I hate to suggest something so drastic. For better or worse, this module relies heavily on the Lability module which I have no control over.
If you had a second computer I'd suggest installing PSAutolab there and seeing if you get the same result. Or, you might completely uninstall this module and the lability module and try again. Run Get-Module psautolab,lability -listavailable to verify you've removed all versions. I'd also make sure C:\Autolab is also gone.

Until I can trace the Lability code this is the best I can come up with.

**Comment by APersondek** [comment] 2019-11-27 18:26
Jeff,

Is there a switch to run setup-lab with verbose screen output, so I can watch to see where it is failing?

Al

**Comment by jdhitsolutions** [comment] 2019-11-27 20:43
Commands have to be written to provide verbose details which I might have to add. You can try running Setup-Lab -verbose but I have no idea if you will see anything.

**Comment by jdhitsolutions** [comment] 2020-02-05 18:34
I still can't duplicate this problem. Just built MultRole with no problem.

```powershell
PS D:\Autolab\Configurations\MultiRole> Get-PSAutoLabSetting


PSVersion     : 5.1.18362.145
PSEdition     : Desktop
OS            : Microsoft Windows 10 Pro
IsElevated    : True
HyperV        : 10.0.18362.1
PSAutolab     : {4.4.0, 4.3.0, 4.1.1, 4.1.0}
Lability      : {0.18.0, 0.12.4}
Pester        : 4.10.0
MemoryGB      : 32
PctFreeMemory : 51.5
```

I'm going to close for now since there's been nothing new in a few months. We can re-open if necessary.

**Comment by roliver88** [comment] 2020-06-19 21:37
Is there an updated set of instructions available that is different than what is discussed in Pluralsight?  I do not have a Setup-Host.ps1  file following the extract all.  Tried working through the detailed instructions and the Readme (found more than 1) and still have not been successful.

**Comment by jdhitsolutions** [comment] 2020-06-19 21:49
I would recommend looking at https://github.com/pluralsight/PS-AutoLab-Env/blob/master/Detailed-Setup-Instructions.md. You need to install the module from the PowerShell Gallery. Do not download from Github.

And yes, many of the Pluralsight courses are referencing the old module. There's nothing to be done about that. But I'm happy to help you. Read the documentation in the README and the detailed setup guide.

**Comment by pete-rapisarda** [comment] 2023-11-16 12:40
I'm having this same problem.  The Diff disks are created, but it seems like there's something wrong with the master vhdx files.  If i delete them and re-run the lab setup the masters get created, but the build fails with an error:

`Building the lab environment for MultiRole-GUI
Failed to start lab configuration.
The semaphore timeout period has expired.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-LabImage
    + PSComputerName        : GNLP-CYACABWHZV`

I think there's something screwy with the way the master disks are created.  I was digging through the code to try and figure it out.  It looks like it's something with lability

@jdhitsolutions how exactly are these created?  Does lability use the ISO files to create them somehow?  I'll keep digging through the code in the meantime but if you (or anyone else) has a quick answer, it would help.

**Comment by jdhitsolutions** [comment] 2023-11-16 13:50
The Lability module downloads ISO images from Microsoft. It is possible the ISO no longer exists. I have. To-do item to update this module and it looks like I need to bump the priority.

**Comment by RoboPete86** [comment] 2023-11-17 12:24
I have a feeling it's something screwy on my laptop.  The vhdx files won't boot.  The iso files download just fine and if I create a fresh VM and install the os using the downloaded isos that works.  So it's something my laptop doesn't like about how these vhdx files are created.  I wouldn't bother yourself too much.  It looks like there's a lability cmdlet that is mounting the isos and generating vhdx files from them but I don't have the bandwidth to keep digging into it.  You can close this if you want.  If I find a solution I'll post it here.

Thanks
-Pete

**Closed** 2024-02-13 15:04 UTC
