### ISSUE TITLE
Why is Invoke-WUUpdate in private.ps1 and public.ps1?

### ISSUE THREAD

**Issue by andreasjordan** [pluralsight/PS-AutoLab-Env#230] opened 2020-06-30 10:53 UTC
I found the commandlet Invoke-WUUpdate in both private.ps1 and public.ps1. Is there a reason for that?

**Comment by jdhitsolutions** [comment] 2020-06-30 11:15
At one point some of that code started as private. I must have copied to public and never cleaned up. I will have to look. Thanks for catching that.

**Comment by jdhitsolutions** [comment] 2020-06-30 13:05
I reviewed the code and cleaned up the mess. Changes will be in v4.15.0. As way of background, the function originally started as a public function but then I created `Update-Lab` which was intended to call the function as a private function. I neglected to clean up the code.

**Comment by jdhitsolutions** [comment] 2020-06-30 15:43
v4.15.0 has been published which corrects this.

**Closed** 2020-06-30 16:21 UTC
Labels: bug
